### ISSUE TITLE
Incorrect field names in range

### ISSUE THREAD

**Issue by duartegarin** [drupal-graphql/graphql-search-api#20]
@joaogarin When we added range delimiters, we assumed that start equals offset (correct) and end equals the end of the range, when in fact it is a "limit".

This means that if I want results on page 2 (on a 5 records per page) I should specify "start" as 5 and "end" as 5.

I propose we refactor this to "offset" and "limit" to be consistent with the rest of GraphQL module implementations.

However, this is a breaking change given that all consumers need to update their implementations.

**Comment by joaogarin** [comment]
This sounds 👍 to me
