### ISSUE TITLE
How to filter for an active facet?

### ISSUE THREAD

**Issue by dermario** [drupal-graphql/graphql-search-api#26]
I could manage to get search_api_graphql working as expected. Now i'm stuck with a question regarding facets parameter input. 

I can query for facets and get the list of available facets back. That's fine. 

```javascript
{
  searchAPISearch(
    index_id: "search_index", 
    language: "de", 
    range: {start: 1, end: 5},
    facets: [
        {operator: "=", field: "field_a", limit: 1, min_count: 0, missing: false}
    	{operator: "=", field: "field_b", limit: 1, min_count: 0, missing: false}
    ]
  ) 
  {
    facets {
      name
      values {
        filter
        count
      }
    }
    documents {
      ... on SearchIndexDoc {
        title
      }
    }
  }
}
```

I get the correct result (that's also fine). 

```javascript
{
  "data": {
    "searchAPISearch": {
      "result_count": 3,
      "facets": [
        {
          "name": "field_a",
          "values": [
            {
              "filter": "34",
              "count": 3
            }
          ]
        },
        {
          "name": "field_a",
          "values": [
            {
              "filter": "35",
              "count": 1
            }
          ]
        },
        {
          "name": "field_b",
          "values": [
            {
              "filter": "42",
              "count": 2
            }
          ]
        },
        {
          "name": "field_b",
          "values": [
            {
              "filter": "10",
              "count": 1
            }
          ]
        }
      ],
      "documents": [
        {
          "title": "Hello World 1"
        },
        {
          "title": "Hello World 2"
        }
      ]
    }
  }
}
```

So here is my question: How can i pass a filtered facet item to the query? So lets say i want to filter for `field_a=34 and field_b=10` and get all results that matches these elements. Is that done with conditions and condition groups (https://graphql-search-api.readthedocs.io/en/latest/search-parameters/#conditions)?

**Comment by duartegarin** [comment]
Hi @scuts ,
That's correct. If a user filters in your frontend, you just pass those parameters as conditions (or condition groups depending on the use case) to the query.

**Comment by dermario** [comment]
Thank you @duartegarin for your quick reply - that's exactly what i need. One last question. I maybe need a *is_active* flag per facet response. I consider checking the conditions somehow and decide whether a facet value is selected. Would that be a valid approach?

**Comment by duartegarin** [comment]
@scuts if I understand you correctly that would be up to your frontend.
In most cases this is achieved by reading the query arguments (or whatever url structure you use) to determine the active facets on a page.

This allows you to open the page directly via a hyperlink (without any user interaction) and immediately select the valid facets.

So the best practice is always to use the url as the source of truth.

As an example, one of our sites:

https://gradnewzealand.nz/search-jobs?locations=796&default=1&study_field_tids=478&start=0

Based on that url the frontend reads the selected facets. If the user adds another one, the url changes and the same cycle happens again.

Hope that makes sense?

Cheers

**Comment by dermario** [comment]
@duartegarin thank you very very much! I really appreciate your help and this exactly the response that i need to get our search app done. All my questions are answered now - so should i will close that issue.

**Comment by duartegarin** [comment]
You're welcome @scuts ,
Good luck with your project!
