### ISSUE TITLE
Conflicts with multiple indexes

### ISSUE THREAD

**Issue by dermario** [drupal-graphql/graphql-search-api#27]
I am facing an issue with two indexes (on two solr cores). When having the same fields e.g. `nid` with an identical machine name in both indexes, this field can only be retrieved for one index.

Lets assume i have 2 indexes: "Index A" and "Index B" and add this field:
![image](https://user-images.githubusercontent.com/8972530/64860366-3d30ee00-d62d-11e9-8f31-8c739333052f.png)

My query looks like this and works, as expected:

```javascript
{
  searchAPISearch(
    index_id: "index_a",
    language: "de",
    range: {start: 1, end: 50}
  ) {
    result_count
    documents {
      ... on IndexADoc {
        nid
      }
    }
}
}
```

For the query to Index B i get `"Cannot query field \"nid\" on type \"IndexBDoc\"`. The schema inspector doesn't show them (only fields that are not in Index A are shown). 

```javascript
{
  searchAPISearch(
    index_id: "index_b",
    language: "de",
    range: {start: 1, end: 50}
  ) {
    result_count
    documents {
      ... on IndexBDoc {
        nid
      }
    }
}
}
```

Renaming the machine name to `nid_1` and modifying the query accordingly works as a workaround.

(Please not, that the queries above are "constructed" manually and not copied 1:1 from my client project. So they might contain an error.)

**Comment by duartegarin** [comment]
Hi @dermario ,
Thank you for reporting, I'll need to have a look as soon as I have a bit more time.
Flagging as bug.
Thanks

**Comment by ayalon** [comment]
This is a critical issue. If you have more than 2 indices, the schema is not correctly generated.

**Comment by ayalon** [comment]
I found the issue. This code is wrong:
graphql_search_api/src/Plugin/GraphQL/Derivers/SearchAPIFieldDeriver.php

```
 foreach ($indexes as $index_id => $index) {
      foreach ($index->getFields() as $field_id => $field) {
        // Define to which Doc type variant the field belongs to.
        $base_plugin_definition['parents'][0] = str_replace("_", "", ucwords($index_id . "Doc", '_'));
        // Initialising derivative settings.
        $this->derivatives[$field_id] = $base_plugin_definition;
        $this->derivatives[$field_id]['id'] = $field_id;
        $this->derivatives[$field_id]['name'] = $field_id;
        // Set field type.
        $this->setFieldType($field, $field_id);
      }
    }
```

If you have 2 fields with the same name on two indexes like 'title', then the parent is only set for the last processed field.

**Fix:**

```
 foreach ($indexes as $index_id => $index) {
      foreach ($index->getFields() as $field_id => $field) {
        if (empty($this->derivatives[$field_id])) {
          // Define to which Doc type variant the field belongs to.
          $base_plugin_definition['parents'][0] = str_replace("_", "", ucwords($index_id . "Doc", '_'));
          // Initialising derivative settings.
          $this->derivatives[$field_id] = $base_plugin_definition;
          $this->derivatives[$field_id]['id'] = $field_id;
          $this->derivatives[$field_id]['name'] = $field_id;
          // Set field type.
          $this->setFieldType($field, $field_id);
        }
        else {
          $this->derivatives[$field_id]['parents'][] = str_replace("_", "", ucwords($index_id . "Doc", '_'));
        }
      }
    }
```

Maybe it would be better to separate the fields per index. If you have a field with the same name but different type on two indices you will run into an issue as well.

**Comment by ayalon** [comment]
Maybe @duartegarin has an opinion on this?

**Comment by rwohleb** [comment]
I've added a PR that includes the index ID in the derivative ID to avoid collisions.
https://github.com/drupal-graphql/graphql-search-api/pull/44

**Comment by carolpettirossi** [comment]
Hi @dermario, @ayalon, and @rwohleb,

Thanks for working to solve this issue. 
I've just tested the PR #44 and it solved it. I've merged to 1.x branch and it will be available in the next release.
