### ISSUE TITLE
Search Highlight Processor

### ISSUE THREAD

**Issue by mslf353** [drupal-graphql/graphql-search-api#31]
I have the search highlight processor enabled but I don't see a way to access it through this API and I saw no mention of it anywhere. Is this something I have to do manually by going through each field which seems very tedious or is there a way to access this?

**Comment by mslf353** [comment]
FYI for anyone else interested, I used the aggregate field and manually made a highlight myself. Probably not the best solution but it works for me for now:

```
let highlight = result.aggregated_field
const highlightIndex = highlight
	.toLowerCase()
	.indexOf(query.toLowerCase())

if (highlightIndex >= 0) {
	let beforeHighlight = highlight.slice(0, highlightIndex)

	if (beforeHighlight.length > 200)
		beforeHighlight = `... ${beforeHighlight.slice(-200)}`

	let afterHighlight = highlight.slice(
		highlightIndex + query.length
	)

	if (afterHighlight.length > 200)
		afterHighlight = `${afterHighlight.slice(0, 200)} ...`

	highlight = `${beforeHighlight}<strong>${highlight.slice(
		highlightIndex,
		highlightIndex + query.length
	)}</strong>${afterHighlight}`
}
```

**Comment by duartegarin** [comment]
Sorry for the very late reply.
We don't really support highlight as of now.
To do this properly it would need to be part of the actual response schema. I'm open to a PR for this but not a priority for now unfortunately.
