### ISSUE TITLE
Using keys return "Internal server error"

### ISSUE THREAD

**Issue by ormarek** [drupal-graphql/graphql-search-api#32]
In any case if I try to use keys, as in example below, in return I get "Internal server error".

```
query {
    searchAPISearch (
        index_id:"content",
        fulltext: {
            keys: "who",
            fields: ["title"]
        }
    ) {
        documents {
            ... on ContentDoc {
                title
            }
        }
    }
}
```
Empty string for keys doesn't throw error but also returns everything. After investigation, conditions also throws the same error

**Comment by duartegarin** [comment]
I'm not being able to replicate this, probably got fixed meanwhile? Closing but reopen if still happens.

**Comment by ormarek** [comment]
@duartegarin Yeah it is fairly old issue tbh and I think I fixed it somehow, don't remember and I can't tell because I currently don't own project I needed this to
