### ISSUE TITLE
Drupal 9 support

### ISSUE THREAD

**Issue by benmyrgorod** [drupal-graphql/graphql-search-api#52]
In order this module work with Drupal 9, it should reply on GraphQL module version 4, but not 3.

**Comment by duartegarin** [comment]
Hi @dealancer ,
That's not correct, GraphQL v3 works with D9.
This module operates solely on v3 and there are no plans to upgrade to v4 as it's a completely different architecture (we are running D9 and use this module in prod).

**Comment by benmyrgorod** [comment]
@duartegarin 

Thanks for quick reply!

Then I was not able to install it using composer. When I require your module via composer for some reason GraphQL version 4 is a dependency and gets installed. When I tell composer to use GraphQL v3, it complains about GraphQL could not work with 9. I am confused as I see GraphQL can work with Drupal 9.

What is the correct way to install your module using composer?

**Comment by duartegarin** [comment]
Hi @dealancer ,
I don't think GraphQL 4 is a dependency, the only stated dependency is graphql itself.
If you install graphql v3 via composer and add it to your build that should perfectly satisfy graphql search api dependency.
Let me know how you go!
